app:
  api:
    github-base-url: https://api.github.com
    stackoverflow-base-url: https://api.stackexchange.com/2.3
    botclient-base-url: http://localhost:8090
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s

spring:
  application:
    name: scrapper

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

logging:
  config: classpath:log4j2-plain.xml
