app:
  telegram-token: ${BOT_TOKEN}


spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

scrapper:
  url: http://localhost:8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
logging:
  config: classpath:log4j2-plain.xml
